apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bo8d49ple-nodejs
  janus-idp.io/tekton: bo8d49ple-nodejs
  backstage.io/kubernetes-id: bo8d49ple-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bo8d49ple-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
