apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bo8d49ple-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bo8d49ple-nodejs 
  name: bo8d49ple-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bo8d49ple-nodejs 
