apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bo8d49ple-nodejs-gitops
  description: This is GitOps manifest for bo8d49ple-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bo8d49ple-nodejs
    backstage.io/kubernetes-id: bo8d49ple-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bo8d49ple-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bo8d49ple-nodejs
